upstream backend {
  server hh_api:8080;

  # maintain 8 connections to the go backend to reduce latency
  keepalive 8;
}

log_format json_analytics escape=json
  '{'
    '"time":"$time_iso8601",'
    '"remoteAddr":"$remote_addr",'
    '"requestID":"$request_id",'
    '"method":"$request_method",'
    '"requestURI":"$request_uri",'
    '"status":$status,'
    '"bodyBytesSent":$body_bytes_sent,'
    '"latency":$request_time,'
    '"upstreamConnectTime":"$upstream_connect_time",'
    '"upstreamResponseTime":"$upstream_response_time",'
    '"httpUserAgent":"$http_user_agent"'
  '}';

server {
  listen 80;

  # static ui files setup
  root /usr/share/nginx/html;
  index index.html;

  # gzip compression
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
  gzip_min_length 1000;

  # enable caching for svelte immutable assets
  location /_app/ {
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
  }

  # fallback for virtual SvelteKit routes
  location / {
    try_files $uri $uri/ /index.html;
  }

  # log formatting
  access_log /dev/stdout json_analytics;
  error_log /dev/stderr warn;

  # ai suggested hardening configs
  # Hide Nginx version from server headers and error pages
  server_tokens off;

  # Prevent MIME-type sniffing (forces browser to respect Content-Type)
  add_header X-Content-Type-Options "nosniff" always;

  # Protect against Clickjacking
  add_header X-Frame-Options "DENY" always;

  # Control referrer information passed to downstream sites
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  # Restrict browser features (camera, microphone, geolocation)
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

  # Limit client request body size (e.g., 2MB max for JSON payloads) - I reduced it to 0 since users will only do get requests
  client_max_body_size 0;

  # Limit header buffer sizes to mitigate slowloris / oversized header attacks
  client_body_buffer_size 16k;
  client_header_buffer_size 1k;
  large_client_header_buffers 4 8k;

  keepalive_timeout 30s;

  # send request id back to user
  add_header X-Request-ID $request_id always;

  location /api/v1 {
    # standard proxy header headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-ID $request_id;

    # re-use persistent TCP connections
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    proxy_pass http://backend;
  }
}
