server {
  listen 80;

  location /api/v1 {
    # clear any incoming X-Request-ID headers and replace it with nginx's own request id
    proxy_set_header X-Request-ID $request_id;

    # standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # return request id to the user
    add_header X-Request-ID $request_id always;
    
    proxy_pass http://hh_api:8080/api/v1;
  }
}
